export const POLL_INTERVAL_MS = 5000;
export const CHUNK_SIZE_BYTES = 3 * 1024 * 1024; // 3 MB
export const SYNC_THRESHOLD_S = 0.5;
export const SEEK_OFFSET_S = 10;
export const LRC_DEFAULT_LINE_DURATION_S = 5;
export const LYRICS_FADE_MIN_OPACITY = 0.1;
export const LYRICS_FADE_OPACITY_DECAY = 0.3;
export const LYRICS_FADE_MIN_SCALE = 0.7;
export const LYRICS_FADE_SCALE_DECAY = 0.1;
export const LYRICS_BLUR_MAX_PX = 4;
export const LYRICS_BLUR_DECAY = 1.5;
export const COUNTDOWN_SHOW_GAP_S = 2;
export const COUNTDOWN_SHOW_REMAINING_S = 3;
export const CATALOG_PAGE_SIZE = 9;
export const LYRICS_WINDOW = 8;
export const UPLOAD_MAX_RETRIES = 3;
export const LRC_OFFSET_STEP_S = 0.5;
export const PLAYBACK_RATES = [0.5, 0.75, 1, 1.25, 1.5, 2] as const;
